-- 01
CREATE TABLE IF NOT EXISTS VERSAO_BASE_DADO (
    VRBD_ID INTEGER NOT NULL,
    VRBD_DATA TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f-0300','now', 'localtime')),
    VRBD_DESCRICAO TEXT NOT NULL,
    VRBD_VERSAO_BASE_DADO TEXT,
    PRIMARY KEY(VRBD_ID)
);
-- 02
CREATE TABLE IF NOT EXISTS UF (
    UF_CD INTEGER NOT NULL,
    UF_NOME TEXT NOT NULL,
    UF_SIGLA TEXT NOT NULL,
    PRIMARY KEY(UF_CD)
);
-- 03
CREATE TABLE IF NOT EXISTS MUNICIPIO (
    MUNI_CD INTEGER NOT NULL,
    MUNI_UF_CD INTEGER NOT NULL,
    MUNI_NOME TEXT NOT NULL,
    FOREIGN KEY(MUNI_UF_CD) REFERENCES UF(UF_CD),
    PRIMARY KEY(MUNI_CD)
);
-- 04
CREATE TABLE IF NOT EXISTS NBS (
    NBS_CD TEXT NOT NULL,
    NBS_DESCRICAO TEXT NOT NULL,
    NBS_LC_116 TEXT DEFAULT NULL,
    NBS_INICIO_VIGENCIA TEXT NOT NULL,
    NBS_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (NBS_FIM_VIGENCIA IS NULL OR NBS_FIM_VIGENCIA >= NBS_INICIO_VIGENCIA),
    PRIMARY KEY(NBS_CD)
);
-- 05
CREATE TABLE IF NOT EXISTS NCM (
    NCM_CD TEXT NOT NULL,
    NCM_DESCRICAO TEXT NOT NULL,
    NCM_INICIO_VIGENCIA TEXT NOT NULL,
    NCM_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (NCM_FIM_VIGENCIA IS NULL OR NCM_FIM_VIGENCIA >= NCM_INICIO_VIGENCIA),
    PRIMARY KEY(NCM_CD)
);
-- 06
CREATE TABLE IF NOT EXISTS UNIDADE_MEDIDA (
    UNMD_ID INTEGER NOT NULL,
    UNMD_SIGLA TEXT NOT NULL,
    UNMD_NOME TEXT NOT NULL,
    UNMD_DESCRICAO TEXT NOT NULL,
    UNMD_INICIO_VIGENCIA TEXT NOT NULL,
    UNMD_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (UNMD_FIM_VIGENCIA IS NULL OR UNMD_FIM_VIGENCIA >= UNMD_INICIO_VIGENCIA),
    PRIMARY KEY(UNMD_ID)
);
-- 07
CREATE TABLE IF NOT EXISTS TRIBUTO (
    TBTO_ID INTEGER NOT NULL,
    TBTO_NOME TEXT NOT NULL,
    TBTO_SIGLA TEXT NOT NULL,
    TBTO_ENTE_FEDERATIVO TEXT NOT NULL CHECK (TBTO_ENTE_FEDERATIVO IN ('UNIÃO', 'ESTADO', 'MUNICÍPIO')),
    TBTO_INICIO_VIGENCIA TEXT NOT NULL,
    TBTO_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (TBTO_FIM_VIGENCIA IS NULL OR TBTO_FIM_VIGENCIA >= TBTO_INICIO_VIGENCIA),
    PRIMARY KEY(TBTO_ID)
);
-- 08
CREATE TABLE IF NOT EXISTS FUNDAMENTACAO_LEGAL (
    FDLG_ID INTEGER NOT NULL,
    FDLG_TEXTO TEXT NOT NULL,
    FDLG_TEXTO_CURTO TEXT NOT NULL,
    FDLG_REFERENCIA_NORMATIVA TEXT NOT NULL,
    FDLG_INICIO_VIGENCIA TEXT NOT NULL,
    FDLG_FIM_VIGENCIA TEXT,
    PRIMARY KEY(FDLG_ID)
);
-- 09
CREATE TABLE IF NOT EXISTS TRATAMENTO_TRIBUTARIO (
    TRTR_ID INTEGER NOT NULL,
    TRTR_DESCRICAO TEXT NOT NULL,
    TRTR_EXPRESSAO_ALIQUOTA TEXT,
    TRTR_EXPRESSAO_ALIQUOTA_EFETIVA TEXT,
    TRTR_EXPRESSAO_BASE_CALCULO TEXT NOT NULL,
    TRTR_EXPRESSAO_TRIBUTO_CALCULADO TEXT NOT NULL,
    TRTR_EXPRESSAO_TRIBUTO_DEVIDO TEXT NOT NULL,
    TRTR_EXPRESSAO_PERCENTUAL_DIFERIMENTO TEXT,
    TRTR_EXPRESSAO_VALOR_DIFERIMENTO TEXT,
    TRTR_IN_INCOMPATIVEL_COM_SUSPENSAO INTEGER NOT NULL,
    TRTR_IN_EXIGE_GRUPO_DESONERACAO INTEGER NOT NULL,
    TRTR_IN_POSSUI_PERCENTUAL_REDUCAO INTEGER NOT NULL,
    TRTR_IN_POSSUI_AJUSTE INTEGER NOT NULL,
    TRTR_IN_POSSUI_REDUTOR INTEGER NOT NULL,
    TRTR_INICIO_VIGENCIA TEXT NOT NULL,
    TRTR_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (TRTR_FIM_VIGENCIA IS NULL OR TRTR_FIM_VIGENCIA >= TRTR_INICIO_VIGENCIA),
    PRIMARY KEY(TRTR_ID)
);
-- 10
CREATE TABLE IF NOT EXISTS SITUACAO_TRIBUTARIA (
    SITR_ID INTEGER NOT NULL,
    SITR_CD TEXT NOT NULL,
    SITR_DESCRICAO TEXT NOT NULL,
    SITR_INICIO_VIGENCIA TEXT NOT NULL,
    SITR_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (SITR_FIM_VIGENCIA IS NULL OR SITR_FIM_VIGENCIA >= SITR_INICIO_VIGENCIA),
    PRIMARY KEY(SITR_ID)
);
-- 11
CREATE TABLE IF NOT EXISTS TOMADOR_ESPECIFICO (
    TMES_ID INTEGER NOT NULL,
    TMES_NOME TEXT NOT NULL,
    TMES_INICIO_VIGENCIA TEXT NOT NULL,
    TMES_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (TMES_FIM_VIGENCIA IS NULL OR TMES_FIM_VIGENCIA >= TMES_INICIO_VIGENCIA),
    PRIMARY KEY(TMES_ID)
);
-- 12
CREATE TABLE IF NOT EXISTS CLASSIFICACAO_TRIBUTARIA (
    CLTR_ID INTEGER NOT NULL,
    CLTR_CD TEXT NOT NULL,
    CLTR_DESCRICAO TEXT NOT NULL,
    CLTR_MEMORIA_CALCULO TEXT NOT NULL,
    CLTR_IN_APROPRIACAO_CREDITOS_ADQUIRENTES_CBS INTEGER,
    CLTR_IN_APROPRIACAO_CREDITOS_ADQUIRENTES_IBS INTEGER,
    CLTR_IN_CREDITO_PRESUMIDO_FORNECEDOR INTEGER,
    CLTR_IN_CREDITO_PRESUMIDO_ADQUIRENTE INTEGER,
    CLTR_SITR_ID INTEGER NOT NULL,
    CLTR_TMES_ID INTEGER,
    CLTR_TIPO_ALIQUOTA TEXT NOT NULL DEFAULT 'Padrão' CHECK (CLTR_TIPO_ALIQUOTA IN (
        'Padrão',
        'Uniforme setorial',
        'Uniforme nacional (referência)',
        'Fixa',
        'Sem alíquota',
        'Alíquotas Combinadas (Ad Valorem e Ad Rem)'
    )),
    CLTR_CREDITO_OPERACAO_ANTECEDENTE TEXT CHECK (CLTR_CREDITO_OPERACAO_ANTECEDENTE IN (
        'Manutenção',
        'Anulação'
    )),
    CLTR_NOMENCLATURA TEXT CHECK (CLTR_NOMENCLATURA IN (
        'NCM',
        'NBS',
        'NBS ou NCM',
        'CIB',
        'CIB ou NCM',
        'Não possui'
    )),
    CLTR_INICIO_VIGENCIA TEXT NOT NULL,
    CLTR_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (CLTR_FIM_VIGENCIA IS NULL OR CLTR_FIM_VIGENCIA >= CLTR_INICIO_VIGENCIA),
    FOREIGN KEY(CLTR_SITR_ID) REFERENCES SITUACAO_TRIBUTARIA(SITR_ID),
    FOREIGN KEY(CLTR_TMES_ID) REFERENCES TOMADOR_ESPECIFICO(TMES_ID),
    PRIMARY KEY(CLTR_ID)
);
-- 13
CREATE TABLE IF NOT EXISTS ANEXO (
    ANXO_ID INTEGER NOT NULL,
    ANXO_NUMERO TEXT,
    ANXO_DESCRICAO TEXT,
    ANXO_NUMERO_ITEM TEXT,
    ANXO_TEXTO_ITEM TEXT,
    ANXO_INICIO_VIGENCIA TEXT NOT NULL,
    ANXO_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ANXO_FIM_VIGENCIA IS NULL OR ANXO_FIM_VIGENCIA >= ANXO_INICIO_VIGENCIA),
    PRIMARY KEY(ANXO_ID)
);
-- 14
CREATE TABLE IF NOT EXISTS NCM_APLICAVEL (
    NCMA_ID INTEGER NOT NULL,
    NCMA_NCM_CD TEXT NOT NULL,
    NCMA_CLTR_ID INTEGER NOT NULL,
    NCMA_ANXO_ID INTEGER,
    NCMA_INICIO_VIGENCIA TEXT NOT NULL,
    NCMA_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (NCMA_FIM_VIGENCIA IS NULL OR NCMA_FIM_VIGENCIA >= NCMA_INICIO_VIGENCIA),
    --FOREIGN KEY(NCMA_NCM_CD) REFERENCES NCM(NCM_CD),
    FOREIGN KEY(NCMA_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(NCMA_ANXO_ID) REFERENCES ANEXO(ANXO_ID),
    PRIMARY KEY(NCMA_ID)
);
-- 15
CREATE TABLE IF NOT EXISTS NBS_APLICAVEL (
    NBSA_ID INTEGER NOT NULL,
    NBSA_NBS_CD TEXT NOT NULL,
    NBSA_CLTR_ID INTEGER NOT NULL,
    NBSA_ANXO_ID INTEGER,
    NBSA_INICIO_VIGENCIA TEXT NOT NULL,
    NBSA_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (NBSA_FIM_VIGENCIA IS NULL OR NBSA_FIM_VIGENCIA >= NBSA_INICIO_VIGENCIA),
    --FOREIGN KEY(NBSA_NBS_CD) REFERENCES NBS(NBS_CD),
    FOREIGN KEY(NBSA_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(NBSA_ANXO_ID) REFERENCES ANEXO(ANXO_ID),
    PRIMARY KEY(NBSA_ID)
);
-- 16
CREATE TABLE IF NOT EXISTS EXCECAO_NCM_APLICAVEL (
    ENCM_ID INTEGER NOT NULL,
    ENCM_NCM_CD TEXT NOT NULL,
    ENCM_NCMA_ID INTEGER NOT NULL,
    ENCM_INICIO_VIGENCIA TEXT NOT NULL,
    ENCM_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ENCM_FIM_VIGENCIA IS NULL OR ENCM_FIM_VIGENCIA >= ENCM_INICIO_VIGENCIA),
    FOREIGN KEY(ENCM_NCMA_ID) REFERENCES NCM_APLICAVEL(NCMA_ID),
    --FOREIGN KEY(ENCM_NCM_CD) REFERENCES NCM(NCM_CD),
    PRIMARY KEY(ENCM_ID)
);
-- 17
CREATE TABLE IF NOT EXISTS EXCECAO_NBS_APLICAVEL (
    ENBS_ID INTEGER NOT NULL,
    ENBS_NBS_CD TEXT NOT NULL,
    ENBS_NBSA_ID INTEGER NOT NULL,
    ENBS_INICIO_VIGENCIA TEXT NOT NULL,
    ENBS_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ENBS_FIM_VIGENCIA IS NULL OR ENBS_FIM_VIGENCIA >= ENBS_INICIO_VIGENCIA),
    FOREIGN KEY(ENBS_NBSA_ID) REFERENCES NBS_APLICAVEL(NBSA_ID),
    --FOREIGN KEY(ENBS_NBS_CD) REFERENCES NBS(NBS_CD),
    PRIMARY KEY(ENBS_ID)
);
-- 18
CREATE TABLE IF NOT EXISTS ALIQUOTA_REFERENCIA (
    ALRE_ID INTEGER,
    ALRE_VALOR REAL NOT NULL,
    ALRE_INICIO_VIGENCIA TEXT NOT NULL,
    ALRE_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ALRE_FIM_VIGENCIA IS NULL OR ALRE_FIM_VIGENCIA >= ALRE_INICIO_VIGENCIA),
    ALRE_TBTO_ID INTEGER NOT NULL,
    FOREIGN KEY(ALRE_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    PRIMARY KEY(ALRE_ID)
);
-- 19
CREATE TABLE IF NOT EXISTS ALIQUOTA_PADRAO (
    ALPA_ID INTEGER,
    ALPA_VALOR REAL NOT NULL,
    ALPA_MUNI_CD INTEGER,
    ALPA_UF_CD INTEGER,
    ALPA_ALRE_ID INTEGER NOT NULL,
    ALPA_FORMA_APLICACAO TEXT NOT NULL CHECK (ALPA_FORMA_APLICACAO IN ('SUBSTITUICAO', 'ACRESCIMO', 'DECRESCIMO')),
    ALPA_INICIO_VIGENCIA TEXT NOT NULL,
    ALPA_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (ALPA_FIM_VIGENCIA IS NULL OR ALPA_FIM_VIGENCIA >= ALPA_INICIO_VIGENCIA),
    FOREIGN KEY(ALPA_ALRE_ID) REFERENCES ALIQUOTA_REFERENCIA(ALRE_ID),
    FOREIGN KEY(ALPA_MUNI_CD) REFERENCES MUNICIPIO(MUNI_CD),
    FOREIGN KEY(ALPA_UF_CD) REFERENCES UF(UF_CD),
    PRIMARY KEY(ALPA_ID)
);
-- 20
CREATE TABLE IF NOT EXISTS ALIQUOTA_AD_VALOREM (
    AADV_ID INTEGER NOT NULL,
    AADV_VALOR REAL NOT NULL,
    AADV_TBTO_ID INTEGER NOT NULL,
    AADV_INICIO_VIGENCIA TEXT NOT NULL,
    AADV_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AADV_FIM_VIGENCIA IS NULL OR AADV_FIM_VIGENCIA >= AADV_INICIO_VIGENCIA),
    FOREIGN KEY(AADV_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    PRIMARY KEY(AADV_ID)
);
-- 21
CREATE TABLE IF NOT EXISTS ALIQUOTA_AD_REM (
    AARE_ID INTEGER NOT NULL,
    AARE_VALOR REAL NOT NULL,
    AARE_UNMD_ID INTEGER NOT NULL,
    AARE_TBTO_ID INTEGER NOT NULL,
    AARE_INICIO_VIGENCIA TEXT NOT NULL,
    AARE_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AARE_FIM_VIGENCIA IS NULL OR AARE_FIM_VIGENCIA >= AARE_INICIO_VIGENCIA),
    FOREIGN KEY(AARE_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    FOREIGN KEY(AARE_UNMD_ID) REFERENCES UNIDADE_MEDIDA(UNMD_ID),
    PRIMARY KEY(AARE_ID)
);
-- 22
CREATE TABLE IF NOT EXISTS ALIQUOTA_AD_VALOREM_PRODUTO (
    AAVP_ID INTEGER NOT NULL,
    AAVP_NCM_CD TEXT NOT NULL,
    AAVP_AADV_ID INTEGER NOT NULL,
    AAVP_INICIO_VIGENCIA TEXT NOT NULL,
    AAVP_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AAVP_FIM_VIGENCIA IS NULL OR AAVP_FIM_VIGENCIA >= AAVP_INICIO_VIGENCIA),
    FOREIGN KEY(AAVP_NCM_CD) REFERENCES NCM(NCM_CD),
    FOREIGN KEY(AAVP_AADV_ID) REFERENCES ALIQUOTA_AD_VALOREM(AADV_ID),
    PRIMARY KEY(AAVP_ID)
);
-- 23
CREATE TABLE IF NOT EXISTS ALIQUOTA_AD_REM_PRODUTO (
    AARP_ID INTEGER NOT NULL,
    AARP_NCM_CD TEXT NOT NULL,
    AARP_AARE_ID INTEGER NOT NULL,
    AARP_INICIO_VIGENCIA TEXT NOT NULL,
    AARP_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AARP_FIM_VIGENCIA IS NULL OR AARP_FIM_VIGENCIA >= AARP_INICIO_VIGENCIA),
    FOREIGN KEY(AARP_NCM_CD) REFERENCES NCM(NCM_CD),
    FOREIGN KEY(AARP_AARE_ID) REFERENCES ALIQUOTA_AD_REM(AARE_ID),
    PRIMARY KEY(AARP_ID)
);
-- 24
CREATE TABLE IF NOT EXISTS ALIQUOTA_AD_VALOREM_SERVICO (
    AAVS_ID INTEGER NOT NULL,
    AAVS_NBS_CD TEXT NOT NULL,
    AAVS_AADV_ID INTEGER NOT NULL,
    AAVS_INICIO_VIGENCIA TEXT NOT NULL,
    AAVS_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AAVS_FIM_VIGENCIA IS NULL OR AAVS_FIM_VIGENCIA >= AAVS_INICIO_VIGENCIA),
    FOREIGN KEY(AAVS_NBS_CD) REFERENCES NBS(NBS_CD),
    FOREIGN KEY(AAVS_AADV_ID) REFERENCES ALIQUOTA_AD_VALOREM(AADV_ID),
    PRIMARY KEY(AAVS_ID)
);
-- 25
CREATE TABLE IF NOT EXISTS ALIQUOTA_AD_REM_SERVICO (
    AARS_ID INTEGER NOT NULL,
    AARS_NBS_CD TEXT NOT NULL,
    AARS_AARE_ID INTEGER NOT NULL,
    AARS_INICIO_VIGENCIA TEXT NOT NULL,
    AARS_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AARS_FIM_VIGENCIA IS NULL OR AARS_FIM_VIGENCIA >= AARS_INICIO_VIGENCIA),
    FOREIGN KEY(AARS_AARE_ID) REFERENCES ALIQUOTA_AD_REM(AARE_ID),
    FOREIGN KEY(AARS_NBS_CD) REFERENCES NBS(NBS_CD),
    PRIMARY KEY(AARS_ID)
);
-- 26
CREATE TABLE IF NOT EXISTS EXCECAO_AD_VALOREM_PRODUTO (
    EAVP_ID INTEGER NOT NULL,
    EAVP_NCM_CD TEXT NOT NULL,
    EAVP_AAVP_ID INTEGER NOT NULL,
    EAVP_INICIO_VIGENCIA TEXT NOT NULL,
    EAVP_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (EAVP_FIM_VIGENCIA IS NULL OR EAVP_FIM_VIGENCIA >= EAVP_INICIO_VIGENCIA),
    FOREIGN KEY(EAVP_NCM_CD) REFERENCES NCM(NCM_CD),
    FOREIGN KEY(EAVP_AAVP_ID) REFERENCES ALIQUOTA_AD_VALOREM_PRODUTO(AAVP_ID),
    PRIMARY KEY(EAVP_ID)
);
-- 27
CREATE TABLE IF NOT EXISTS EXCECAO_AD_REM_PRODUTO (
    EARP_ID INTEGER NOT NULL,
    EARP_NCM_CD TEXT NOT NULL,
    EARP_AARP_ID INTEGER NOT NULL,
    EARP_INICIO_VIGENCIA TEXT NOT NULL,
    EARP_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (EARP_FIM_VIGENCIA IS NULL OR EARP_FIM_VIGENCIA >= EARP_INICIO_VIGENCIA),
    FOREIGN KEY(EARP_NCM_CD) REFERENCES NCM(NCM_CD),
    FOREIGN KEY(EARP_AARP_ID) REFERENCES ALIQUOTA_AD_REM_PRODUTO(AARP_ID),
    PRIMARY KEY(EARP_ID)
);
-- 28
CREATE TABLE IF NOT EXISTS EXCECAO_AD_VALOREM_SERVICO (
    EAVS_ID INTEGER NOT NULL,
    EAVS_NBS_CD TEXT NOT NULL,
    EAVS_AAVS_ID INTEGER NOT NULL,
    EAVS_INICIO_VIGENCIA TEXT NOT NULL,
    EAVS_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (EAVS_FIM_VIGENCIA IS NULL OR EAVS_FIM_VIGENCIA >= EAVS_INICIO_VIGENCIA),
    FOREIGN KEY(EAVS_NBS_CD) REFERENCES NBS(NBS_CD),
    FOREIGN KEY(EAVS_AAVS_ID) REFERENCES ALIQUOTA_AD_VALOREM_SERVICO(AAVS_ID),
    PRIMARY KEY(EAVS_ID)
);
-- 29
CREATE TABLE IF NOT EXISTS EXCECAO_AD_REM_SERVICO (
    EARS_ID INTEGER NOT NULL,
    EARS_NBS_CD TEXT NOT NULL,
    EARS_AARS_ID INTEGER NOT NULL,
    EARS_INICIO_VIGENCIA TEXT NOT NULL,
    EARS_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (EARS_FIM_VIGENCIA IS NULL OR EARS_FIM_VIGENCIA >= EARS_INICIO_VIGENCIA),
    FOREIGN KEY(EARS_NBS_CD) REFERENCES NBS(NBS_CD),
    FOREIGN KEY(EARS_AARS_ID) REFERENCES ALIQUOTA_AD_REM_SERVICO(AARS_ID),
    PRIMARY KEY(EARS_ID)
);
-- 30
CREATE TABLE IF NOT EXISTS PERCENTUAL_REDUCAO (
    PERE_ID INTEGER NOT NULL,
    PERE_CLTR_ID INTEGER NOT NULL,
    PERE_TBTO_ID INTEGER NOT NULL,
    PERE_VALOR REAL NOT NULL,
    PERE_INICIO_VIGENCIA TEXT NOT NULL,
    PERE_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (PERE_FIM_VIGENCIA IS NULL OR PERE_FIM_VIGENCIA >= PERE_INICIO_VIGENCIA),
    FOREIGN KEY(PERE_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(PERE_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID), 
    PRIMARY KEY(PERE_ID)
);
-- 31
CREATE TABLE IF NOT EXISTS AJUSTE (
    AJST_ID INTEGER NOT NULL,
    AJST_CLTR_ID INTEGER NOT NULL,
    AJST_TBTO_ID INTEGER NOT NULL,
    AJST_VALOR REAL NOT NULL,
    AJST_INICIO_VIGENCIA TEXT NOT NULL,
    AJST_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (AJST_FIM_VIGENCIA IS NULL OR AJST_FIM_VIGENCIA >= AJST_INICIO_VIGENCIA),
    FOREIGN KEY(AJST_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(AJST_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    PRIMARY KEY(AJST_ID)
);
-- 32
CREATE TABLE IF NOT EXISTS REDUTOR (
    RDTO_ID INTEGER NOT NULL,
    RDTO_CLTR_ID INTEGER NOT NULL,
    RDTO_TBTO_ID INTEGER NOT NULL,
    RDTO_VALOR REAL NOT NULL,
    RDTO_INICIO_VIGENCIA TEXT NOT NULL,
    RDTO_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (RDTO_FIM_VIGENCIA IS NULL OR RDTO_FIM_VIGENCIA >= RDTO_INICIO_VIGENCIA),
    FOREIGN KEY(RDTO_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(RDTO_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    PRIMARY KEY(RDTO_ID)
);
-- 33
CREATE TABLE IF NOT EXISTS TRATAMENTO_CLASSIFICACAO (
    TRCL_ID INTEGER NOT NULL,
    TRCL_CLTR_ID INTEGER NOT NULL,
    TRCL_TRTR_ID INTEGER NOT NULL,
    TRCL_INICIO_VIGENCIA TEXT NOT NULL,
    TRCL_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (TRCL_FIM_VIGENCIA IS NULL OR TRCL_FIM_VIGENCIA >= TRCL_INICIO_VIGENCIA),
    FOREIGN KEY(TRCL_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(TRCL_TRTR_ID) REFERENCES TRATAMENTO_TRIBUTARIO(TRTR_ID),
    PRIMARY KEY(TRCL_ID)
);
-- 34
CREATE TABLE IF NOT EXISTS FUNDAMENTACAO_CLASSIFICACAO (
    FDCL_ID INTEGER NOT NULL,
    FDCL_CLTR_ID INTEGER NOT NULL,
    FDCL_FDLG_ID INTEGER NOT NULL,
    FDCL_INICIO_VIGENCIA TEXT NOT NULL,
    FDCL_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (FDCL_FIM_VIGENCIA IS NULL OR FDCL_FIM_VIGENCIA >= FDCL_INICIO_VIGENCIA),
    FOREIGN KEY(FDCL_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(FDCL_FDLG_ID) REFERENCES FUNDAMENTACAO_LEGAL(FDLG_ID),
    PRIMARY KEY(FDCL_ID)
);
-- 35
CREATE TABLE IF NOT EXISTS APROPRIACAO_CREDITO_ADQUIRENTE (
    APCA_ID INTEGER NOT NULL,
    APCA_FDLG_ID INTEGER,
    APCA_CLTR_ID INTEGER NOT NULL,
    APCA_TBTO_ID INTEGER NOT NULL,
    APCA_INICIO_VIGENCIA TEXT NOT NULL,
    APCA_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (APCA_FIM_VIGENCIA IS NULL OR APCA_FIM_VIGENCIA >= APCA_INICIO_VIGENCIA),
    FOREIGN KEY(APCA_FDLG_ID) REFERENCES FUNDAMENTACAO_LEGAL(FDLG_ID),
    FOREIGN KEY(APCA_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
    FOREIGN KEY(APCA_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    PRIMARY KEY(APCA_ID)
);
-- 36
CREATE TABLE IF NOT EXISTS TRIBUTO_SITUACAO_TRIBUTARIA (
    TRST_ID INTEGER NOT NULL,
    TRST_SITR_ID INTEGER NOT NULL,
    TRST_TBTO_ID INTEGER NOT NULL,
    TRST_INICIO_VIGENCIA TEXT NOT NULL,
    TRST_FIM_VIGENCIA TEXT DEFAULT NULL CHECK (TRST_FIM_VIGENCIA IS NULL OR TRST_FIM_VIGENCIA >= TRST_INICIO_VIGENCIA),
    FOREIGN KEY(TRST_SITR_ID) REFERENCES SITUACAO_TRIBUTARIA(SITR_ID),
    FOREIGN KEY(TRST_TBTO_ID) REFERENCES TRIBUTO(TBTO_ID),
    PRIMARY KEY(TRST_ID)
);